export enum CHALLENGE_STATE {
  UPCOMING = "UPCOMING",
  ONGOING = "ONGOING",
  PROCESSING = "PROCESSING",
  PAYINGOUT = "PAYINGOUT",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  NO_WINNER = "NO_WINNER",
  NO_WINNER_PAYINGOUT = "NO_WINNER_PAYINGOUT",
  CANCELLED_PAYINGOUT = "CANCELLED_PAYINGOUT",
}

export enum ONCHAIN_STATE {
  TO_BE_MINTED = "TO_BE_MINTED",
  MINTED = "MINTED",
  UPDATED = "UPDATED",
  TRANSFERRED = "TRANSFERRED",
  CANCELLED = "CANCELLED",
  NO_WINNER = "NO_WINNER",
}

export enum VERIFIED_CURRENCY {
  CREDITS = "CREDITS",
  USDC = "USDC",
  SOL = "SOL",
  SOL_DEVNET = "SOL_DEVNET",
  BONK = "BONK",
  SEND = "SEND",
}

export enum CHALLENGE_CATEGORIES {
  FITNESS = "Fitness",
  ART = "Art",
  TRAVEL = "Travel",
  ADVENTURE = "Adventure",
  LIFESTYLE = "Lifestyle",
  GAMING = "Gaming",
  SPORTS = "Sports",
  SOCIAL_MEDIA = "Social Media",
  EVENT = "Event",
  RANDOM = "Random",
}

export enum PARTICIPATION_TYPE {
  ZERO_VS_ONE = 0,
  ONE_VS_ONE = 1,
  NVN = 2,
}

export enum GAME_TYPE {
  STEPS = 0,
  CALORIES = 1,
  DIGITAL_PROOF = 2,
  VALIDATOR = 3,
  VOTING = 4,
}

export enum ParticipationTypeMultiToken {
  SIDE_BET = "SideBet",
  JOIN_CHALLENGE = "JoinChallenge",
}

export enum NotificationMedium {
  APP_NOTIF = "APP_NOTIF",
  PUSH_NOTIF = "PUSH_NOTIF",
  EMAIL = "EMAIL",
}

export enum NOTIFICATION_TYPE {
  SIGNUP = "SIGNUP",
  CHALLENGE_CREATED = "CHALLENGE_CREATED",
  CHALLENGE_JOINED_SELF = "CHALLENGE_JOINED_SELF",
  CHALLENGE_JOINED_PLAYER = "CHALLENGE_JOINED_PLAYER",
  CHALLENGE_JOINED_CREATOR = "CHALLENGE_JOINED_CREATOR",
  CHALLENGE_MAX_PARTICIPATION_REACHED_CREATOR = "CHALLENGE_MAX_PARTICIPATION_REACHED_CREATOR",
  CHALLENGE_MAX_PARTICIPATION_REACHED_PLAYER = "CHALLENGE_MAX_PARTICIPATION_REACHED_PLAYER",
  CHALLENGE_CANCELLED_SELF = "CHALLENGE_CANCELLED_SELF",
  CHALLENGE_CANCELLED_PLAYER = "CHALLENGE_CANCELLED_PLAYER",
  CHALLENGE_STARTED_SELF = "CHALLENGE_STARTED_SELF",
  CHALLENGE_STARTED_PLAYER = "CHALLENGE_STARTED_PLAYER",
  CHALLENGE_ENDED_SELF = "CHALLENGE_ENDED_SELF",
  CHALLENGE_ENDED_PLAYER = "CHALLENGE_ENDED_PLAYER",
  CHALLENGE_SETTLED_WITH_NO_WINNER = "CHALLENGE_SETTLED_WITH_NO_WINNER",
  CHALLENGE_SETTLED_WITH_NO_WINNER_CREATOR = "CHALLENGE_SETTLED_WITH_NO_WINNER_CREATOR",
  CHALLENGE_SETTLED_WITH_WINNER_SELF = "CHALLENGE_SETTLED_WITH_WINNER_SELF",
  CHALLENGE_SETTLED_WITH_WINNER_CREATOR = "CHALLENGE_SETTLED_WITH_WINNER_CREATOR",
  CHALLENGE_SETTLED_WITH_WINNER = "CHALLENGE_SETTLED_WITH_WINNER",
  WITHDRAW_REQUEST = "WITHDRAW_REQUEST",
  WITHDRAW_SUCCESS = "WITHDRAW_SUCCESS",
  WITHDRAW_FAILED = "WITHDRAW_FAILED",
  DEPOSIT_REQUEST = "DEPOSIT_REQUEST",
  DEPOSIT_SUCCESS = "DEPOSTI_SUCCESS",
  DEPOSIT_FAILED = "DEPOSIT_FAILED",
}

export enum GENDER {
  MALE = "male",
  FEMALE = "female",
  OTHER = "others",
  UNKNOWN = "unknown",
}

export enum WALLET_TYPES {
  OKTO = "OKTO",
  EXTERNAL = "EXTERNAL",
}

export enum AdditionalNotificationType {
  OKTO = "OKTO",
}

export enum REFUND_STATE {
  NOT_ELIGIBLE = "NOT_ELIGIBLE",
  ELIGIBLE = "ELIGIBLE",
  REFUND_PROCESSING = "REFUND_PROCESSING",
  REFUNDED = "REFUNDED",
}

export enum WITHDRAW_STATE {
  CREATE = "CREATE",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
}

export enum CONNECTED_WALLET_TYPES {
  OKTO = "OKTO",
  BROWSER = "BROWSER",
  DEEPLINK = "DEEPLINK",
}

export enum ONCHAIN_PARTICIPATE_TYPE {
  JOIN_CHALLENGE = "joinChallenge",
  SIDE_BET = "sideBet",
}

export enum VIEW_TYPE {
  DEEP_LINK_VIEW = "Deeplinkview",
  EXTENSION_WALLET_VIEW = "ExtensionWalletview",
  OKTO_WALLET_VIEW = "OktoWallet",
  TIPLINK_WALLET_VIEW = "TiplinkView",
}

export enum LOCALSTORAGE_ITEMS {
  SHARED_SECRET = "sharedSecret",
  SESSION = "session",
  WALLET_ADDRESS = "walletAddress",
  DAPP_KEY_PAIR = "dappKeyPair",
  VERIFICATION_MESSAGE = "verificationMessage",
  ACCESS_TOKEN = "accessToken",
  REFRESH_TOKEN = "refreshToken",
}

export enum DEEP_LINK_FUNCTIONS {
  SIGN_MESSAGE = "signMessage",
  CONNECT = "connect",
  DISCONNECT = "disconnect",
  SIGN_AND_SEND_TRANSACTION = "signAndSendTransaction",
}
